from snakemake.utils import min_version

min_version("6.10.0")


configfile: "config/config.yml"


# declare https://github.com/ZandvakiliLab/fastq-prep-and-align as a module
module fastq_prep_and_align:
    snakefile:
        github(
            "ZandvakiliLab/fastq-prep-and-align",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/fastq-prep-and-align
use rule * from fastq_prep_and_align


# ─────────────────────────────────────────────────────────────────────────────
# 3. Module rule Modification
# ─────────────────────────────────────────────────────────────────────────────

use rule align_star_index from fastq_prep_and_align as align_star_index with:
    input:
        fasta="results/genome/genome.fasta",
        gtf="results/genome/genome.gff",
    threads: 8

use rule align_deeptools_coverage from fastq_prep_and_align as align_deeptools_coverage with:
    params:
        effective_genome_size=lambda wc: config["mapping_stats"]["deeptools_coverage"][
            "genome_size"
        ][wc.genome],
        extra=lambda wc: (
            config["mapping_stats"]["deeptools_coverage"]["extra"]
            + " --normalizeUsing {norm}".format(
                norm=config["mapping_stats"]["deeptools_coverage"]["normalizeUsing"]
            )
            + " --filterRNAstrand {strand}".format(
                strand="forward" if wc.strand == "minus" else "reverse"
            )
        ),


use rule prereads_multiqc from fastq_prep_and_align as prereads_multiqc with:
    input:
        lambda wc: fastq_prep_and_align.prepreads.get_multiqc_input(wc)
        + fastq_prep_and_align.align.get_multiqc_input(wc),


# ─────────────────────────────────────────────────────────────────────────────
# container definition (optional)
# ─────────────────────────────────────────────────────────────────────────────
container: "oras://ghcr.io/zandvakililab/fastq-prep-and-align:latest"
